export const NODE_TYPES = {
    FILE: 'file',
    FOLDER: 'folder',
  };
  
  
export const ACTION_TYPES = {
    TOGGLE_CONTENT_VISIBILITY: 'TOGGLE_CONTENT_VISIBILITY',
    FETCH_DIRECTORIES: 'FETCH_DIRECTORIES',
    ERROR_FETCH_DIRECTORIES: 'ERROR_FETCH_DIRECTORIES',
    SET_DIRECTORIES: "SET_DIRECTORIES",
  };
  